# Generated by Django 4.2.11 on 2026-06-07 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='游戏时间')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='游戏地点')),
                ('game_type', models.CharField(choices=[('mahjong_16', '16张麻将'), ('mahjong_13', '13张麻将'), ('guangdong', '广东麻将'), ('sichuan', '四川麻将'), ('other', '其他')], default='mahjong_16', max_length=20, verbose_name='游戏类型')),
                ('base_score', models.IntegerField(default=1, help_text='每分对应的金额（元）', verbose_name='基础分值')),
                ('is_supplemental', models.BooleanField(default=False, verbose_name='是否为补录')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rooms.room', verbose_name='关联房间')),
            ],
            options={
                'verbose_name': '游戏记录',
                'verbose_name_plural': '游戏记录列表',
                'ordering': ['-game_time'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='正数为赢，负数为输', verbose_name='得分')),
                ('rank', models.IntegerField(default=1, verbose_name='排名')),
                ('is_winner', models.BooleanField(default=False, verbose_name='是否获胜')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '游戏玩家',
                'verbose_name_plural': '游戏玩家列表',
                'ordering': ['-score'],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_type', models.CharField(choices=[('domination', '全场通吃'), ('comeback', '反败为胜'), ('big_win', '大胜局'), ('rare_pattern', '稀有牌型'), ('other', '其他精彩')], default='other', max_length=20, verbose_name='高光类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('highlight_score', models.IntegerField(default=0, help_text='自动计算的精彩程度评分', verbose_name='精彩评分')),
                ('is_comeback', models.BooleanField(default=False, verbose_name='是否逆转')),
                ('comeback_deficit', models.IntegerField(default=0, verbose_name='最大落后分')),
                ('is_domination', models.BooleanField(default=False, verbose_name='是否全场通吃')),
                ('domination_score', models.IntegerField(default=0, verbose_name='通吃分数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '高光时刻',
                'verbose_name_plural': '高光时刻列表',
                'ordering': ['-highlight_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TilePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='牌型名称')),
                ('category', models.CharField(choices=[('special', '特殊牌型'), ('color', '花色牌型'), ('honor', '字牌牌型'), ('basic', '基础牌型'), ('combo', '组合牌型'), ('custom', '自定义')], default='basic', max_length=20, verbose_name='牌型类别')),
                ('fan_count', models.IntegerField(default=1, verbose_name='番数')),
                ('description', models.TextField(blank=True, verbose_name='牌型描述')),
                ('rarity_score', models.IntegerField(default=1, help_text='1-10, 用于高光时刻评分', verbose_name='稀有度评分')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '麻将牌型',
                'verbose_name_plural': '麻将牌型列表',
                'ordering': ['-rarity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0, verbose_name='总场次')),
                ('wins', models.IntegerField(default=0, verbose_name='胜场')),
                ('losses', models.IntegerField(default=0, verbose_name='负场')),
                ('win_rate', models.FloatField(default=0.0, verbose_name='胜率')),
                ('total_score', models.IntegerField(default=0, verbose_name='总得分')),
                ('avg_score', models.FloatField(default=0.0, verbose_name='场均得分')),
                ('max_score', models.IntegerField(default=0, verbose_name='最高单场得分')),
                ('min_score', models.IntegerField(default=0, verbose_name='最低单场得分')),
                ('max_consecutive_wins', models.IntegerField(default=0, verbose_name='最大连胜')),
                ('max_consecutive_losses', models.IntegerField(default=0, verbose_name='最大连败')),
                ('current_consecutive_wins', models.IntegerField(default=0, verbose_name='当前连胜')),
                ('current_consecutive_losses', models.IntegerField(default=0, verbose_name='当前连败')),
                ('domination_count', models.IntegerField(default=0, verbose_name='全场通吃次数')),
                ('comeback_count', models.IntegerField(default=0, verbose_name='逆转胜利次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '玩家统计',
                'verbose_name_plural': '玩家统计列表',
            },
        ),
        migrations.CreateModel(
            name='HighlightCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='games.highlight', verbose_name='高光')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_collections', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '高光收藏',
                'verbose_name_plural': '高光收藏列表',
                'ordering': ['-created_at'],
                'unique_together': {('highlight', 'user')},
            },
        ),
        migrations.AddField(
            model_name='highlight',
            name='collected_by',
            field=models.ManyToManyField(blank=True, related_name='collected_highlights', through='games.HighlightCollection', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='games.game', verbose_name='游戏'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL, verbose_name='主角'),
        ),
        migrations.CreateModel(
            name='GameSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='局数')),
                ('cumulative_score', models.IntegerField(verbose_name='累计分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='games.game', verbose_name='游戏')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '分数快照',
                'verbose_name_plural': '分数快照列表',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayerPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_self_draw', models.BooleanField(default=False, verbose_name='是否自摸')),
                ('zhongma_count', models.IntegerField(default=0, verbose_name='中码数量')),
                ('consecutive_dealer', models.IntegerField(default=0, verbose_name='连庄次数')),
                ('round_number', models.IntegerField(default=1, verbose_name='第几局')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='games.gameplayer', verbose_name='游戏玩家')),
                ('shooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot_patterns', to=settings.AUTH_USER_MODEL, verbose_name='点炮者')),
                ('tile_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_occurrences', to='games.tilepattern', verbose_name='牌型')),
            ],
            options={
                'verbose_name': '牌型记录',
                'verbose_name_plural': '牌型记录列表',
            },
        ),
    ]
