# Generated by Django 4.2.11 on 2026-06-07 06:47

import apps.rooms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房间名称')),
                ('code', models.CharField(default=apps.rooms.models.generate_room_code, max_length=10, unique=True, verbose_name='房间码')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('playing', '游戏中'), ('finished', '已结束')], default='waiting', max_length=20, verbose_name='状态')),
                ('game_type', models.CharField(choices=[('mahjong_16', '16张麻将'), ('mahjong_13', '13张麻将'), ('guangdong', '广东麻将'), ('sichuan', '四川麻将'), ('other', '其他')], default='mahjong_16', max_length=20, verbose_name='游戏类型')),
                ('max_players', models.IntegerField(default=4, verbose_name='最大人数')),
                ('base_score', models.IntegerField(default=1, help_text='每分对应的金额（元）', verbose_name='基础分值')),
                ('description', models.TextField(blank=True, verbose_name='房间描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL, verbose_name='房主')),
            ],
            options={
                'verbose_name': '游戏房间',
                'verbose_name_plural': '游戏房间列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃状态')),
                ('is_ready', models.BooleanField(default=False, verbose_name='准备状态')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '房间成员',
                'verbose_name_plural': '房间成员列表',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
